apiVersion: v1
kind: Service
metadata:
  namespace: konga
  name: kong-service
spec:
  ports:
  - port: 1337
    targetPort: 1337
    name: konga-ui
    protocol: TCP
  selector:
    app: kong-frontend